### ISSUE TITLE
Question about differences in dividend reinvestment events in money market vs. non-money-market listed funds.

### ISSUE THREAD

**Issue by savingsandloan** [redstreet/reds-ramblings-comments#14]
Hi, I'm still playing with your vanguard qfx importer and have a question in how it handles investment/sale events for 'money_market' funds. For example, I have a vanguard importer setup under the following config:

```vanguard_fund_info = {
        'fund_data': [
            ('VMFXX', '922906300', 'Vanguard Federal Money Market Fund'),
            ('VMMXX', '922906201', 'Vanguard Prime Money Market Fund'),
        ],
        'money_market': ['VMMXX'],
}
```

From there I'm noticing a difference between two similar reinvestment events where for **VMFXX** an event will look like:

```
<REINVEST>
<INVTRAN><FITID>999999999<DTTRADE>20200529160000.000[-5:EST]<DTSETTLE>20200529160000.000[-5:EST]<MEMO>DIVIDEND REINVESTMENTDIVIDEND REINVESTMENT</INVTRAN>
<SECID><UNIQUEID>922906300<UNIQUEIDTYPE>CUSIP</SECID>
<INCOMETYPE>DIV<TOTAL>-0.25<SUBACCTSEC>CASH<UNITS>0.25<UNITPRICE>1.0</REINVEST>
```

Will look like: 

```
2020-05-29 * "DIVIDEND REINVESTMENTDIVIDEND REINVESTMENT" "[VMFXX] Vanguard Federal Money Market Fund"
  file_account: "Assets:US:Vanguard:Brokerage"
  Assets:Vanguard:Brokerage:VMFXX             0.25 VMFXX {1.0 USD}
  Income:Vanguard:Brokerage:Dividends:VMFXX  -0.25 USD
```

but an event for **VMMXX**: 

```
<REINVEST><INVTRAN><FITID>999999999<DTTRADE>20200529160000.000[-5:EST]<DTSETTLE>20200529160000.000[-5:EST]
<MEMO>DIVIDEND REINVESTMENTDIVIDEND REINVESTMENT</INVTRAN>
<SECID><UNIQUEID>922906201<UNIQUEIDTYPE>CUSIP</SECID>
<INCOMETYPE>DIV<TOTAL>-0.25<SUBACCTSEC>CASH<UNITS>0.25<UNITPRICE>1.0</REINVEST>
```
will look like:

```
2020-05-29 * "DIVIDEND REINVESTMENTDIVIDEND REINVESTMENT" "[VMMXX] Vanguard Prime Money Market Fund"
  file_account: "Assets:US:Vanguard:Brokerage"
  Assets:Vanguard:Brokerage:VMMXX             0.25 VMMXX @ 1.0 USD
  Income:Vanguard:Brokerage:Dividends:VMMXX  -0.25 USD            
```

Question 1:  Why does VMMXX look different? Is it because I have it confugured as a money_market fund? I assume writing something like 1 XXX @ 1.0 USD only applied to selling an asset or am I wrong?

Question 2: This might be a semantics argument, but is there a reason you prefer writing the account as `Income:Vanguard:Brokerage:Dividends:VMFXX` instead of `Income:Vanguard:Brokerage:VMFXX:Dividends`? 

Largely curious to understand your importer design/conventions better. I've wrote a csv-based vanguard importer a while back (slightly more featured to handle 'exchange' events but requires massaging the csv a bit and needs some small improvements to be open sourced), but considering what else has been done to be more collaborative and have looked through your other writings about why you're going the qfx route: https://reds-rants.netlify.app/personal-finance/make-importers-easy-to-write-and-write-lots-of-them/

**Comment by redstreet** [comment]
http://reds-rants.netlify.app/personal-finance/ledger-filing-hierarchy/
